name: Compile, lint and test on all branches

on:
  push:
    branches:
      - *

jobs:
  pr:
    strategy:
      matrix:
        step: ['build', 'lint', 'test']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.step }}
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn ${{ matrix.step }}
